### ISSUE TITLE
forward method in transformer class

### ISSUE THREAD

**Issue by akkasi** [hkproj/pytorch-transformer#10]
Hi,
It seems there is something wrong with transformer class. It does not have a forward method! could you please clarify the reason? Tnx

**Comment by hkproj** [comment]
Hi! The forward method is not needed, as we apply the encoder and decoder "by hand": https://github.com/hkproj/pytorch-transformer/blob/1af7967a312913ecb4801ea432d5648c58762f0d/train.py#L234
