### ISSUE TITLE
Truncation for Tokenizer

### ISSUE THREAD

**Issue by ardaaras99** [hkproj/pytorch-transformer#12]
For people with low resources, you might want to add a truncation option for tokens. For instance:

  # Truncation
  if self.seq_len < len(enc_input_tokens):
      enc_input_tokens = enc_input_tokens[: self.seq_len - 2]

  if self.seq_len < len(dec_input_tokens):
      dec_input_tokens = dec_input_tokens[: self.seq_len - 1]

Changing padding accordingly, 
  # Padding

  enc_num_pad_tokens = max(0, self.seq_len - len(enc_input_tokens) - 2)
  dec_num_pad_tokens = max(0, self.seq_len - len(dec_input_tokens) - 1)

**Comment by hkproj** [comment]
Thanks for your tutorial!
