### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by debby-2020** [hkproj/pytorch-transformer#9]
@hkproj how do I use my own dataset in this transformer?. The language I want to use as my dataset is not on hugging face, I collected it myself and it is in excel format. Please sir can you respond to me and teach me me what to do.

**Comment by hkproj** [comment]
Hi! Since your custom dataset is already in Excel, you can export it as CSV and import it into Hugging Face's dataset format. This is a nice tutorial on how to do exactly that: https://saturncloud.io/blog/how-to-load-custom-dataset-from-csv-in-hugging-faces-transformers-a-comprehensive-guide/

**Comment by debby-2020** [comment]
sir please can you give a step by step approach to do this yourself because
the tutorial was not of help. I will so much appreciate your help sir.

**Comment by debby-2020** [comment]
Sir please can you give a step by step approach to do this yourself because
the tutorial was not of help. I will so much appreciate your help sir. How
do I finetune your code sir?
